// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.yutax77.model;

import com.yutax77.model.BookIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect BookIntegrationTest_Roo_Configurable {
    
    declare @type: BookIntegrationTest: @Configurable;
    
}
