// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.yutax77.model;

import com.yutax77.model.Review;
import com.yutax77.model.ReviewDataOnDemand;
import com.yutax77.model.ReviewIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ReviewIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ReviewIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ReviewIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ReviewIntegrationTest: @Transactional;
    
    @Autowired
    private ReviewDataOnDemand ReviewIntegrationTest.dod;
    
    @Test
    public void ReviewIntegrationTest.testCountReviews() {
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", dod.getRandomReview());
        long count = Review.countReviews();
        Assert.assertTrue("Counter for 'Review' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ReviewIntegrationTest.testFindReview() {
        Review obj = dod.getRandomReview();
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Review' failed to provide an identifier", id);
        obj = Review.findReview(id);
        Assert.assertNotNull("Find method for 'Review' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Review' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ReviewIntegrationTest.testFindAllReviews() {
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", dod.getRandomReview());
        long count = Review.countReviews();
        Assert.assertTrue("Too expensive to perform a find all test for 'Review', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Review> result = Review.findAllReviews();
        Assert.assertNotNull("Find all method for 'Review' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Review' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ReviewIntegrationTest.testFindReviewEntries() {
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", dod.getRandomReview());
        long count = Review.countReviews();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Review> result = Review.findReviewEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Review' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Review' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ReviewIntegrationTest.testFlush() {
        Review obj = dod.getRandomReview();
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Review' failed to provide an identifier", id);
        obj = Review.findReview(id);
        Assert.assertNotNull("Find method for 'Review' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyReview(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Review' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewIntegrationTest.testMergeUpdate() {
        Review obj = dod.getRandomReview();
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Review' failed to provide an identifier", id);
        obj = Review.findReview(id);
        boolean modified =  dod.modifyReview(obj);
        Integer currentVersion = obj.getVersion();
        Review merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Review' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ReviewIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", dod.getRandomReview());
        Review obj = dod.getNewTransientReview(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Review' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Review' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Review' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ReviewIntegrationTest.testRemove() {
        Review obj = dod.getRandomReview();
        Assert.assertNotNull("Data on demand for 'Review' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Review' failed to provide an identifier", id);
        obj = Review.findReview(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Review' with identifier '" + id + "'", Review.findReview(id));
    }
    
}
