// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.yutax77.model;

import com.yutax77.model.Review;

privileged aspect Review_Roo_JavaBean {
    
    public String Review.getWriter() {
        return this.writer;
    }
    
    public void Review.setWriter(String writer) {
        this.writer = writer;
    }
    
}
